# Generated by Django 2.2.4 on 2019-09-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190908_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature1',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='feature2',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='feature3',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='feature4',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='feature5',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
