# Generated by Django 2.2.4 on 2019-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190911_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
