# Generated by Django 2.2.4 on 2019-09-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190911_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='Feature', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature1',
            field=models.CharField(default='Feature', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature2',
            field=models.CharField(default='Feature', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature3',
            field=models.CharField(default='Feature', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature4',
            field=models.CharField(default='Feature', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature5',
            field=models.CharField(default='Feature', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='Feature', max_length=30),
        ),
    ]
